version: '3.7'

services:
  webserver:
    build:
      context: .
      dockerfile: dockerfile
    container_name: server1
    restart: unless-stopped
    tty: true
    environment:
      - ASPNETCORE_URLS=http://+:80
    networks:
      - api-net
